package RandomerUtils;

/*

    Project     ED21
    Package     Endevinador    
    
    Version     1.0      
    Author      Carlos Pomares
    Date        2020-12-10

    DESCRIPTION
    
*/

/**
 * @author Carlos Pomares
 */

public class RandomerGenerator {

    /**
     *
     * Returns true o false is the numberIntroduced is lower or higher than the hiddenNumber.
     *
     * @param numberIntroduced number introduced by the user.
     * @param hiddenNumber number generated by the application.
     * @return true o false if the input number is lower than the number introduced.
     */
    public static boolean generateHint(int numberIntroduced, int hiddenNumber){
        return numberIntroduced < hiddenNumber;
    }

    /**
     *
     * Returns a string if the 'polarize' param is true o false. It's complemented by the generateHint type boolean.
     *
     * @param polarize the boolean input given by the generateHint type boolean.
     * @return a given string of 'Número más alto' or 'Número más bajo'
     */
    public static String generateHint(boolean polarize){
        return (polarize) ? "Número más alto" : "Número más bajo";
    }

    /**
     *
     * Check if the number given is equal to hiddenNumber.
     *
     * @param playerNumber the player input number.
     * @param hiddenNumber the generated hidden number.
     * @return if the playerNumber is equal to hiddenNumber.
     */
    public static boolean checkNumber(int playerNumber,int hiddenNumber){ return playerNumber == hiddenNumber; }

    /**
     *
     * Generate number by the given number to reach.
     *
     * @param numberToReach the maximum number to reach.
     * @return a random number by given range.
     */
    public static int generateNumber(int numberToReach){
        return (int)(Math.random() * (numberToReach + 1));
    }

}
